### ISSUE TITLE
Conflict babel/register?

### ISSUE THREAD

**Issue by kjirou** [kjirou/reproduce-power-assert-bug#1]
### Success

```
$(npm bin)/mocha --compilers js:espower-babel/guess test/index.js
$(npm bin)/mocha --require espower-babel-loader test/index.js
$(npm bin)/mocha --require babel/register --require espower-babel-loader test/index.js
```

### Failure

```
$(npm bin)/mocha --require babel/register --compilers js:espower-babel/guess test/index.js
$(npm bin)/mocha --require espower-babel-loader --require babel/register test/index.js
```

**Comment by kjirou** [comment]
`node_modules/mocha/bin/_mocha`:
```
309 // requires
310 
311 requires.forEach(function(mod) {
312   console.log('By requires.forEach:', mod);
313   require(mod);
314 });
```

```
$(npm bin)/mocha --require babel/register --require espower-babel/guess test/index.js
By requires.forEach: babel/register
By requires.forEach: espower-babel/guess

(Success)
```

```
%$(npm bin)/mocha --require babel/register --compilers js:espower-babel/guess test/index.js
By requires.forEach: babel/register

(Failure)
```

**Comment by twada** [comment]
What a strange behavior...
Hmm, `espower-babel` does not work after `babel/register` ?
Do you have any ideas @azu ?

**Comment by azu** [comment]
> $(npm bin)/mocha --require babel/register --compilers js:espower-babel/guess test/index.js

What’s your use case?

It is expected behavior I think.
This mean that espower-babel overwrite [`extension["js"]`](https://github.com/power-assert-js/espower-babel/blob/2ac56cd17953c4c001a938c49bda0321138e8113/index.js#L46-L69) and babel/register does too, then conflict it.

These function has duplicating role(espower-babel and babel/register).

Does Babel + [babel-plugin-espower](https://github.com/power-assert-js/babel-plugin-espower "babel-plugin-espower") fulfill your demand?

----

[babelrc](http://babeljs.io/docs/usage/babelrc/ "babelrc")

```json
{
  "plugins": [
    "babel-plugin-espower"
  ]
}
```

ref: [es2015 - babel-nodeでbabel pulginsを使うには.babelrcを設定する - Qiita](http://qiita.com/ledsun/items/e6a5b994e3ece89e81ca "es2015 - babel-nodeでbabel pulginsを使うには.babelrcを設定する - Qiita")

**Comment by kjirou** [comment]
@azu @twada Thank you for your reply!!!

In conclusion, my problem was solved by the knowledge of the following.

> This mean that espower-babel overwrite extension["js"] and babel/register does too, then conflict it.

----

It may be unnecessary, my use case is the following situation:

- ES6 and ES5 mixed in the project
- Not transpling
  - So that, describe `require('babel/register')` in the first `.js` file (`app.js`, `index.js` etc)
- All test files are written by ES6
- Become to conflict `babel/register`, when tests are run by `mocha --compilers js:espower-babel/guess`

**Comment by twada** [comment]
@kjirou As a result, is this solved?

**Comment by kjirou** [comment]
@twada Yes, it is. Thanks a lot.

**Comment by twada** [comment]
Glad to hear that :smiley_cat:
